# Project 1: Loan Default Prediction

This project aims to predict whether a loan will be fully paid or charged off using Lending Club data.

In [ ]:
import os
os.listdir()

['.config', 'accepted_2007_to_2018Q4.csv', 'drive', 'sample_data']

اتأكد ان موجوده ال Dataset

import os استخدمه لتعامل مع نظام الملفات


os.listdir() استخدمه ليعرض الملفات الموجوده مثل csv

## Import Libraries
We import the required Python libraries for data manipulation and machine learning.

In [ ]:
import pandas as pd
import numpy as np

نزلت المكتبات الاساسيه لل Data \3

pandas مكتبه لمعالجه البيانات علشان تقرا csv

 ولتنظيف وتحليل البيانات

numpy مكتبه علشان تتعامل مع الارقام

للعمليات الرياضية مهمه لاحقا للنمذجه

## Load Dataset
The Lending Club dataset is loaded from a CSV file.

In [ ]:
df=pd.read_csv("accepted_2007_to_2018Q4.csv")

/tmp/ipython-input-1432470458.py:1: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("accepted_2007_to_2018Q4.csv")

خليته يقرا ملف البيانات حق csv \4

df نستخدمه علشان نخزن فيه البيانات كمتغير يعني

df=DataFrame وش هو؟

*   جدول
*   صفوف+اعمده




pd
csvاستخدمته لاني ابي اقرا البيانات بملف ال

In [ ]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN



*  يعرض اول 5 صفوف
*  يعطيني اسم الاعمده و شكل البيانات وهل هو نصوص او ارقام
ولو احط 1 بين القوسين بيعرض لي اول صف فقط

In [ ]:
df.shape

(7004, 151)



*   يعطي عدد الصفوف والاعمده كلها

## Feature Selection
We selected relevant features related to loan amount, income, debt, and borrower profile.

In [ ]:
selected_columns = [
   'loan_amnt',
   'annual_inc'  ,
   'home_ownership' ,
   'dti'    ,
   'delinq_2yrs',
   'term',
   'int_rate',
   'loan_status'
]
df_selected = df[selected_columns]



*  هنا حددت وانشئت قائمه بالاعمده المهمه الي احتاجها احقق الهدف

In [ ]:
df_selected.head()

,loan_amnt,annual_inc,home_ownership,dti,delinq_2yrs,term,int_rate,loan_status
0,3600.0,55000.0,MORTGAGE,5.91,0.0,36 months,13.99,Fully Paid
1,24700.0,65000.0,MORTGAGE,16.06,1.0,36 months,11.99,Fully Paid
2,20000.0,63000.0,MORTGAGE,10.78,0.0,60 months,10.78,Fully Paid
3,35000.0,110000.0,MORTGAGE,17.06,0.0,60 months,14.85,Current
4,10400.0,104433.0,MORTGAGE,25.37,1.0,60 months,22.45,Fully Paid

اتاكد انه سوا الاعمده الي حددتها له

In [ ]:
df_selected.isnull().sum()

loan_amnt         0
annual_inc        0
home_ownership    0
dti               0
delinq_2yrs       0
term              0
int_rate          0
loan_status       0
dtype: int64

يفحص لي اذا فيه قيم مفقوده /ناقصه isnull
يرجع لي True\False

يجمع عدد القيم المفقوده في كل عامود  sum

0 مافي
رقم اكبر من 0 فيه

In [ ]:
df_selected.dtypes

loan_amnt         float64
annual_inc        float64
home_ownership     object
dti               float64
delinq_2yrs       float64
term               object
int_rate          float64
loan_status        object
dtype: object

يعطيني نوع بيانات كل عامود سوا رقم ام نص dtypes

In [ ]:
df_selected['term']=df_selected['term'].str.replace('months', '')

/tmp/ipython-input-703329538.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_selected['term']=df_selected['term'].str.replace('months', '')

هنا حذفت كلمه months
وحولتها ل رقم

يعني من نص الى رقم
object to int

## Target Variable Definition
The target variable is loan_status, classified as Fully Paid or Charged Off.

In [ ]:
df_selected = df_selected[
    df_selected['loan_status'].isin(['Fully Paid','Charged Off'])
]
df_selected['loan_status']=df_selected['loan_status'].map({
    'Fully Paid':0 ,
    'Charged Off':1
})

حالة القرض انواع ولكن صنفته على اساس الهدف اما متعثر او غير متعثر
,مدفوع بالكامل 1
مشطوب 0

In [ ]:
df_selected.dtypes
df_selected['loan_status'].value_counts()

loan_status
0    5060
1    1182
Name: count, dtype: int64

هنا0 معناه عندي قروض مسدده بالكامل عددها =7045

1والي لا هو

مسدده اكثر وتعثر اقل هذا يسمى imbalance

In [ ]:
df_selected.isnull().mean()*100

loan_amnt         0.0
annual_inc        0.0
home_ownership    0.0
dti               0.0
delinq_2yrs       0.0
term              0.0
int_rate          0.0
loan_status       0.0
dtype: float64

هنا كويس تاكدت بعد مافي قيم ناقصه

## Categorical Encoding
Categorical variables were converted into numerical format using one-hot encoding.

In [ ]:
if 'home_ownership' in df_selected.columns:
    df_selected = pd.get_dummies(
        df_selected,columns=['home_ownership'],
        drop_first=True
    )
else:
    print("The 'home_ownership' column has already been processed or does not exist.")



*   pd.get_dummies ليه استخدمناه لان يحول النصوص الى اعمده رقميه


*    columns=['home_ownership'] هنا حددت العمود الي ابي احوله

drop_first=True ثم حذفت اول شيئ يعتبر متغير وهمي


One-hot encondingطريقه تحويل ذي كانت الى اعمده مستقله استخدمت ال

In [ ]:
df_selected.columns

Index(['loan_amnt', 'annual_inc', 'dti', 'delinq_2yrs', 'term', 'int_rate',
       'loan_status', 'home_ownership_OWN', 'home_ownership_RENT'],
      dtype='object')

home_ownership انحذف / تحول

وجاء بداله home_ownership_OWN وhome_ownership_RENT

In [ ]:
#قلت له ان جميع الاعمده عباره عن X , ماعدا الهدف حذفته

x= df_selected.drop('loan_status',axis=1)

#هنا قلت له ترا Y, هو الهدف

y = df_selected['loan_status']

#avoid data leakage

نقسم البيانات الى

Target(Y) and Features(X)

X نحدد ال (المتغيرات)

Y نحدد ال (الهدف)

#لفصل المتغيرات عن الهدف لتجنب تسرب البيانات

In [ ]:
print(x.shape)
print(y.shape)

(6242, 8)
(6242,)

علشان نتاكد انه صح

## Train-Test Split
The dataset was split into training and testing sets to evaluate model performance and avoid overfitting.

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(
    x , y , test_size=0.2 , random_state=42 ,
    stratify=y
)

test_size=0.2 لما قلت

اقصد فيه 20% اختبار

و80% تدريب

random_state=42  يخلي النتائج ثابته كل مره

ومهم للتكرار والتقييم

stratify=y يحافظ على نسبه المتعثرين والمسددين

مهم جدا لان البيانات غير متوازيه

In [ ]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

loan_status
0    0.810735
1    0.189265
Name: proportion, dtype: float64
loan_status
0    0.810248
1    0.189752
Name: proportion, dtype: float64

نتحقق ومفروض تكون النسب متقاربه

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)
#

#StandardScaler

هنا استخدم توحيد المقاييس لان بعض المتغيرات قيمها كبيره وبعضها صغيره

لو ماوحدناه النموذج ينحاز الى الارقام الكبيره
ونتائج تصير غير عادله

## Model 1: Logistic Regression
Logistic Regression was chosen for its simplicity and interpretability in credit risk prediction.

In [ ]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight='balanced'

)
model.fit(x_train_scaled,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000)

#LogisticRegression اول مودل



*   بسيط و قابل للتفسير
*   مناسب للbinary classification

In [ ]:
y_pred = model.predict(x_test_scaled)

y_proba = model.predict_proba(x_test_scaled)[:,1]

التوقع النهائي 1 او 0 y_pred

احتمال التعثر y_proba

In [ ]:
from sklearn.metrics import roc_auc_score , confusion_matrix , classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

roc_auc = roc_auc_score(y_test,y_proba)
print("ROC AUC  : ",roc_auc)

[[707 305]
 [ 81 156]]
              precision    recall  f1-score   support

           0       0.90      0.70      0.79      1012
           1       0.34      0.66      0.45       237

    accuracy                           0.69      1249
   macro avg       0.62      0.68      0.62      1249
weighted avg       0.79      0.69      0.72      1249

ROC AUC  :  0.7366163005953871

التقييم

## Model Explainability
Feature importance was analyzed using Logistic Regression coefficients to understand key risk drivers.

In [ ]:
import pandas as pd
feature_importance = pd.DataFrame(
    {'feature':x.columns , 'coefficient':model.coef_[0]}
).sort_values(by='coefficient',ascending=False)

feature_importance

               feature  coefficient
5             int_rate     0.624865
4                 term     0.268743
7  home_ownership_RENT     0.193933
2                  dti     0.158418
6   home_ownership_OWN     0.119890
3          delinq_2yrs     0.095688
0            loan_amnt     0.087290
1           annual_inc    -0.139442

تفسير النموذج


*   الاداره تبغى تفهم
*  البنوك تبرر قرارتها

اذا المعامل موجب = يزيد احتماليه التعثر

اذا المعامل سالب = يقلل احتماليه التعثر

## Model 2: Decision Tree Classifier
A Decision Tree model was trained to capture non-linear relationships in the data.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

# تدريب النموذج
dt_model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42
)

dt_model.fit(x_train, y_train)

# التنبؤ
y_pred_dt = dt_model.predict(x_test)

# التقييم
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Decision Tree Accuracy: 0.8078462770216173
              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1012
           1       0.48      0.13      0.21       237

    accuracy                           0.81      1249
   macro avg       0.65      0.55      0.55      1249
weighted avg       0.76      0.81      0.76      1249

## Model Comparison
The performance of both models was compared using accuracy and classification metrics.

In [ ]:
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred))

Logistic Regression Accuracy: 0.6909527622097679
Decision Tree Accuracy: 0.6909527622097679

## Conclusion
This project demonstrates how machine learning can support loan default prediction.
Future improvements may include handling class imbalance and testing more advanced models.